version: "3.9"

name: trainium

services:
  kong:
    image: kong:3.6
    env_file:
      - .env
    depends_on:
      - frontend
      - agents
      - jobspy_service
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_LOG_LEVEL: "${KONG_LOG_LEVEL}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN}"
      KONG_PLUGINS: "bundled,cors,request-transformer"
    volumes:
      - ./gateway/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "${KONG_PROXY_PORT}:8000"   # public proxy
      - "${KONG_ADMIN_PORT}:8001"   # admin api (dev only)
    networks: [trainium-net]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "8080"
    networks: [trainium-net]
    restart: unless-stopped

  agents:
    build: ./agents
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      # LLM keys (also pulled from env_file)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    expose:
      - "8000"
    networks: [trainium-net]
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2 --proxy-headers

  jobspy_service:
    build: ./jobspy_service
    expose:
      - "8000"
    networks: [trainium-net]
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2 --proxy-headers

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [trainium-net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
    networks: [trainium-net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  trainium-net:

volumes:
  pgdata:
  mongodata:
